election/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^voting/', include('voting.urls')),
    url(r'^admin/', admin.site.urls),
]

voting/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views
from .views import *
from django.contrib import admin
admin.autodiscover()
router = routers.DefaultRouter()
router.register(r'users', views.CustomUserViewSet)
router.register(r'states', views.StateViewSet)
router.register(r'seats', views.SeatViewSet, base_name="Seat")
router.register(r'booths', views.BoothViewSet, base_name="Booth")


urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', 'django.contrib.auth.views.login'),
    url(r'^api/', include(router.urls)),
    url(r'^logout/$', logout_page),
    url(r'^register/$', register),
    url(r'^register/success/$', register_success),
    url(r'^home/$', home),
    url(r'^vote/$', vote),
    url(r'^update_election_status/$', update_election_status),
    url(r'^count_vote/$', count_vote),
    url(r'^result_count/(?P<level>state|seat|country)/(?P<id>\d+)$', result_count),
    url(r'^add_state/$', add_state),
    url(r'^add_seat/$', add_seat),
    url(r'^add_booth/$', add_booth),
    url(r'^admin/', include(admin.site.urls)),
]

voting/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager
)

class StateManager(models.Manager):
    def get_by_natural_key(self, id):
        return self.get(pk=id)

class State(models.Model):
    name = models.CharField(max_length=200, unique=True)
    vote_counted = models.BooleanField(default=False)
    participated_in_voting = models.BooleanField(default=False)
    objects = StateManager()

    def __str__(self):
        return "%s" % (self.name)

class Seat(models.Model):
    name = models.CharField(max_length=200)
    state = models.ForeignKey(State)
    vote_counted = models.BooleanField(default=False)
    participated_in_voting = models.BooleanField(default=False)
    class Meta:
        unique_together = ('state', 'name',)

    def __str__(self):
        return "%s" % (self.name)

class Booth(models.Model):
    name = models.CharField(max_length=200)
    seat = models.ForeignKey(Seat)

    class Meta:
        unique_together = ('seat', 'name',)

    def __str__(self):
        return "%s" % (self.name)

class Party(models.Model):
    name = models.CharField(max_length=200, unique=True)
    num_seats_won = models.IntegerField(default=0)

    def __str__(self):
        return "%s" % (self.name)

    class Meta:
        verbose_name_plural = 'Parties'

SEX = (('M', 'MALE'), ('F', 'FEMALE'))

class CustomUserManager(BaseUserManager):
    def create_user(self, first_name, voter_id, last_name=None, sex=None, date_of_birth=None, password=None):
        user = self.model(
            first_name=first_name,
            last_name=last_name,
            date_of_birth=date_of_birth,
            sex=sex,
            voter_id=voter_id
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, voter_id, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            first_name='admin',
            last_name='',
            password=password,
            voter_id=voter_id
        )
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user

class CustomUser(AbstractBaseUser):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField(null=True)
    sex = models.CharField(choices=SEX, max_length=10, null=True)
    voter_id = models.CharField(max_length=40, unique=True)
    booth = models.ForeignKey(Booth, null=True)
    casted_vote = models.BooleanField(default=False)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'voter_id'

    objects = CustomUserManager()

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    def get_full_name(self):
        return self.first_name+" "+self.last_name

    def get_short_name(self):
        return self.first_name

voting/views.py
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from rest_framework import generics
from django.conf import settings
import operator
from .models import *
import os, pdb
import redis

@csrf_protect
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            print "In register request = "+ str(request.POST)
            form.save()
            return HttpResponseRedirect('/voting/register/success/')
    else:
        form = RegistrationForm()
    variables = RequestContext(request, {
    'form': form
    })
    return render_to_response(
    'registration/register.html',
    variables,
    )

def register_success(request):
    print "In success request = "+ str(request)
    return render_to_response(
    'registration/success.html',
    )

def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/voting/')

@login_required
def home(request):
    r = redis.StrictRedis(host='localhost', port=6379)
    IS_ELECTION_DONE = r.get("IS_ELECTION_DONE")
    return render_to_response(
    'home.html',
    { 'user': request.user,
      'is_election_done' : IS_ELECTION_DONE=="true"
    },
    context_instance=RequestContext(request)
    )

@login_required
def add_state(request):
    error_message=""
    if request.method == 'POST':
        if 'state_name' in request.POST:
            name = request.POST['state_name']
        try:
            if name and 'state_id' in request.POST and request.POST['state_id'] and request.POST['state_id']:
                state = State.objects.get(pk=request.POST['state_id'])
                state.name = name
                state.save()
            elif name:
                State.objects.create(name=name)
            else:
                state = State.objects.get(pk=request.POST['state_id'])
                state.delete()
            return HttpResponseRedirect('/voting/home/')
        except:
            error_message="Either input is invalid or a state with same name already exists!"
    return render_to_response('add_state.html', {'states' : State.objects.all(), 'error_message' : error_message}, context_instance=RequestContext(request))

@login_required
def add_seat(request):
    error_message=""
    if request.method == 'POST':
        name = request.POST['seat_name']
        state_id = request.POST['state_id']
        try:
            if name and state_id and 'seat_id' in request.POST and request.POST['seat_id']:
                seat = Seat.objects.get(pk=request.POST['seat_id'])
                seat.name = name
                seat.save()
            elif name and state_id:
                Seat.objects.create(name=name, state_id=state_id)
            else:
                seat = Seat.objects.get(pk=request.POST['seat_id'])
                seat.delete()
            return HttpResponseRedirect('/voting/home/')
        except:
            error_message="Either input is invalid or a seat with same name already exists!"
    return render_to_response('add_seat.html', {'states' : State.objects.all(), 'error_message' : error_message},
                              context_instance=RequestContext(request))

@login_required
def add_booth(request):
    error_message=""
    if request.method == 'POST':
        name = request.POST['booth_name']
        seat_id = request.POST['seat_id']
        try:
            if name and seat_id and 'booth_id' in request.POST and request.POST['booth_id']:
                booth = Booth.objects.get(pk=request.POST['booth_id'])
                booth.name = name
                booth.save()
            elif name and seat_id:
                Booth.objects.create(name=name, seat_id=seat_id)
            else:
                booth = Booth.objects.get(pk=request.POST['booth_id'])
                booth.delete()
            return HttpResponseRedirect('/voting/home/')
        except:
            error_message="Either input is invalid or a booth with same name already exists!"
    return render_to_response('add_booth.html', {'states': State.objects.all(), 'error_message' : error_message},
                              context_instance=RequestContext(request))

@login_required
def vote(request):
    if request.method == 'POST':
        user = CustomUser.objects.get(voter_id=request.POST['user'])
        user.casted_vote = True
        user.save()

        seat = user.booth.seat
        seat.participated_in_voting = True
        seat.save()

        state = seat.state
        state.participated_in_voting = True
        state.save()

        party = Party.objects.get(id=request.POST['party_name'])
        party_name = party.name
        # num_seats_own = party.num_seats_won
        # num_seats_own += 1
        # party.num_seats_won = num_seats_own
        # party.save()

        booth = user.booth
        seat_name = booth.seat.name

        dir = 'voting_data/'+seat_name
        if not os.path.exists(dir):
            os.mkdir(dir)

        file_name = dir+"/booth"+'-'+str(booth.id)+".txt"
        f = open(file_name, 'a+' )
        f.write(party_name+"\n")
        f.close()

        return HttpResponseRedirect('/voting/home/')
    user = request.user
    if user.casted_vote:
        return HttpResponseRedirect('/voting/home/')
    return render_to_response(
        'cast_vote.html',
        { 'user': request.user,
          'parties': Party.objects.all()
        },
        context_instance=RequestContext(request)
    )

@login_required
def update_election_status(request):
    if request.method == 'POST':
        r = redis.StrictRedis(host='localhost', port=6379)
        IS_ELECTION_DONE = r.get("IS_ELECTION_DONE")
        if not IS_ELECTION_DONE:
            r.set("IS_ELECTION_DONE", "true")
        else:
            if IS_ELECTION_DONE == "true":
                IS_ELECTION_DONE = "false"
            else:
                IS_ELECTION_DONE = "true"
            r.set("IS_ELECTION_DONE", IS_ELECTION_DONE)
        return HttpResponse("<a href='/voting/count_vote/'>Count Votes</a>")


@login_required
def count_vote(request):
    if request.method == 'POST':
        level=None
        id=None
        if request.POST.get('level')=='seat' and 'seat_id' in request.POST and request.POST['seat_id']:
            seat_id = request.POST['seat_id']
            state_id = request.POST['state_id']
            level='seat'
            id=seat_id
            seat = Seat.objects.get(pk=seat_id)
            seat.vote_counted = True
            seat.save()
            from voting.tasks import seat_count
            seat_count.delay(seat_id, state_id)

        elif request.POST.get('level')=='state' and 'state_id' in request.POST:
            state_id = request.POST['state_id']
            state = State.objects.get(pk=state_id)
            level='state'
            id=state_id
            state.vote_counted = True
            state.save()
            from voting.tasks import state_count
            state_count.delay(state_id)
        else:
            level='country'
            id=0
            from voting.tasks import country_count
            country_count.delay()
        return HttpResponseRedirect('/voting/result_count/'+level+'/'+str(id))
    states = State.objects.filter(participated_in_voting=True)
    return render_to_response('count_votes.html', {'user': request.user, 'states':states},  context_instance=RequestContext(request))

@login_required
def result_count(request, level, id):
    flag = False
    if level=="state":
        line = "STATE LEVEL RESULT<br><br>"
        state = State.objects.get(pk=id)
        if os.path.exists('voting_data/State'+str(id)+'/count'):
            lines = [l.rstrip('\n') for l in open('voting_data/State'+str(id)+'/count')]
            parties_with_votes = [l.split("\t") for l in lines]
            winner = max(parties_with_votes, key=operator.itemgetter(1))[0]

            line += "Winner for "+state.name+" is "+winner+"<br>"
            flag = True
    elif level=="seat":
        line  = "DISTRICT LEVEL RESULT<br><br>"
        seat = Seat.objects.get(pk=id)
        if os.path.exists('voting_data/District'+str(id)+'/count'):
            lines = [l.rstrip('\n') for l in open('voting_data/District'+str(id)+'/count')]
            parties_with_votes = [l.split("\t") for l in lines]
            winner_count = max(parties_with_votes, key=operator.itemgetter(1))
            winner = winner_count[0]
            count = winner_count[1]
            line += "Winner for "+seat.name+" under "+seat.state.name+" is "+winner+" with count = "+str(count)+"<br>"
            flag = True
    else:
        line  = "COUNTRY LEVEL RESULT<br><br>"
        if os.path.exists('voting_data/Country/count'):
            lines = [l.rstrip('\n') for l in open('voting_data/Country/count')]
            parties_with_votes = [l.split("\t") for l in lines]
            winner = max(parties_with_votes, key=operator.itemgetter(1))[0]

            line += "Winner for country is "+winner+"<br>"
            flag = True
    if flag:
        line += "<a href='/voting/home/'>Home</a>"
        return HttpResponse(line)
    return render_to_response(
        "result.html",
        {'level':level, 'id':id},
        context_instance=RequestContext(request)
    )


from rest_framework import viewsets
from voting.serializers import CustomUserSerializer, StateSerializer, SeatSerializer, BoothSerializer
from .models import *

class CustomUserViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all().order_by('voter_id')
    serializer_class = CustomUserSerializer

class StateViewSet(viewsets.ModelViewSet):
    queryset = State.objects.all().order_by('name')

voting/templates/add_booth.html
{% extends "base.html" %}
{% block title %}Add/Modify/Delete booth{% endblock %}
{% block head %}Add/Modify/Delete booth{% endblock %}
{% block content %}
<p><a href="/voting/home/">Home</a></p>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
     <form method="post" action="/voting/add_booth/">{% csrf_token %}
         <table border="0">
             <tr><th><label for="id_option">Option:</label></th>
                 <td>
                <select name="option" id="option_id_booth">
                    <option value="">Select Option</option>
                    <option value="add">Add</option>
                    <option value="modify">Modify</option>
                    <option value="delete">Delete</option>
                </select>
             </td></tr>
            <tr><th><label for="id_state" id="label_state">State Name:</label></th>
                <td>
                 <select name="state_id" class="state_id" id="id_state">
                     <option>Select state</option>
                    {% for state in states %}
                        <option value="{{ state.id }}">{{ state.name }}</option>
                    {% endfor %}
                 </select>
                </td>
            </tr>
             <tr><th><label for="seat_name" id="seat_name">District Name:</label></th>
                <td>
                 <select name="seat_id" class="seat_id" id="id_seat">
                     <option>Select seat</option>
                 </select>
                </td>
            </tr>
             <tr><th><label for="booth_label" id="booth_label_id">Existing booth:</label></th>
                <td>
                 <select name="booth_id" id="id_booth">
                     <option value="">Select a booth</option>
                 </select>
                </td>
            </tr>
            <tr><th><label for="booth_name" id="label_booth_name">Booth Name:</label></th>
                <td><input type="text" name="booth_name" id="booth_name"></td>
            </tr>
             <tr><td><input type="submit" value="Submit"></td></tr>
         </table>
     </form>
{% endblock %}

voting/templates/add_seat.html
{% extends "base.html" %}
{% block title %}Add/Modify/Delete district{% endblock %}
{% block head %}Add/Modify/Delete district{% endblock %}
{% block content %}
<p><a href="/voting/home/">Home</a></p>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
     <form method="post" action="/voting/add_seat/">{% csrf_token %}
         <table border="0">
             <tr><th><label for="id_option">Option:</label></th>
                 <td>
                <select name="option" id="option_id_seat">
                    <option value="">Select Option</option>
                    <option value="add">Add</option>
                    <option value="modify">Modify</option>
                    <option value="delete">Delete</option>
                </select>
             </td></tr>
            <tr><th><label for="id_state">State Name:</label></th>
                <td>
                 <select name="state_id" id="id_state">
                     <option value="">Select a state</option>
                    {% for state in states %}
                        <option value="{{ state.id }}">{{ state.name }}</option>
                    {% endfor %}
                 </select>
                </td>
            </tr>
             <tr><th><label for="seat_label" id="seat_label_id">Existing district:</label></th>
                <td>
                 <select name="seat_id" id="id_seat">
                     <option value="">Select a district</option>
                 </select>
                </td>
            </tr>
            <tr><th><label for="seat_name" id="label_seat_name">District Name:</label></th>
                <td><input type="text" name="seat_name" id="seat_name"></td>
            </tr>
             <tr><td><input type="submit" value="Submit"></td></tr>
         </table>
     </form>
{% endblock %}

voting/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title>Election Application |
        {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                    return cookieValue;
                }
                $('.datepicker').datepicker();
                if(!$('.state_id').is('#id_state')){
                    $('.state_id').attr('id', 'id_state');
                }

                $('#option_id').on('change', function() {
                    if($('#option_id').val() == "add"){
                      $("#add_state_id").empty().append('<option selected="selected" value="">Select a seat</option>')
                      $("#add_state_id").css("visibility", "hidden");
                      $('#state_name').val("");
                      $('#state_name').removeAttr("style");
                      $('#state_label').removeAttr("style");
                    }else if($('#option_id').val() == "modify"){
                       $('#add_state_id').removeAttr("style");
                       $('#state_name').removeAttr("style");
                       $('#state_label').removeAttr("style");
                    }else if($('#option_id').val() == "delete"){
                       $('#add_state_id').removeAttr("style");
                       $('#state_name').val("");
                       $('#state_name').css("visibility", "hidden");
                       $('#state_label').css("visibility", "hidden");
                    }
                });

                $('#option_id_seat').on('change', function() {
                    if($('#option_id_seat').val() == "add"){
                      $("#id_seat").empty().append('<option selected="selected" value="">Select a seat</option>')
                      $("#id_seat").css("visibility", "hidden");
                      $('#seat_label_id').css("visibility", "hidden");
                      $('#seat_name').val("");
                      $('#label_seat_name').removeAttr("style");
                    }else if($('#option_id_seat').val() == "delete"){
                       $('#id_seat').removeAttr("style");
                       $('#seat_label_id').removeAttr("style");
                       $('#seat_name').css("visibility", "hidden");
                       $('#label_seat_name').css("visibility", "hidden");
                    }else if($('#option_id_seat').val() == "modify"){
                       $('#id_seat').removeAttr("style");
                       $('#seat_label_id').removeAttr("style");
                       $('#seat_name').removeAttr("style");
                       $('#seat_name').val("");
                       $('#label_seat_name').removeAttr("style");
                    }
                });

                $('#option_id_booth').on('change', function() {
                    if($('#option_id_booth').val() == "add"){
                      $("#id_booth").css("visibility", "hidden");
                      $("#id_booth").empty().append('<option selected="selected" value="">Select a booth</option>')
                      $('#booth_label_id').css("visibility", "hidden");
                      $('#booth_name').val("");
                      $('#label_booth_name').removeAttr("style");
                    }else if($('#option_id_booth').val() == "delete"){
                       $('#id_booth').removeAttr("style");
                       $('#booth_label_id').removeAttr("style");
                       $('#booth_name').css("visibility", "hidden");
                       $('#label_booth_name').css("visibility", "hidden");
                    }else if($('#option_id_booth').val() == "modify"){
                       $('#id_booth').removeAttr("style");
                       $('#booth_label_id').removeAttr("style");
                       $('#booth_name').removeAttr("style");
                       $('#booth_name').val("");
                       $('#label_booth_name').removeAttr("style");
                    }
                });

                $('#add_state_id').on('change', function(){
                    if($('#option_id_seat').val() == "modify"){
                        $('#state_name').val($('#add_state_id option:selected').text());
                    }else{
                       $('#state_name').val("");
                    }
                });
                $('#id_state').trigger('change');
                $('#id_state').on('change', function() {
                    $.ajax({
                        url: '/voting/api/seats/',
                        dataType: 'json',
                        type: 'GET',
                        data: {state_id : $('#id_state').val()},
                        success: function(data) {
                            $('#id_seat').empty();
                            for (row in data) {
                                $('#id_seat').append($('<option></option>').attr('value', data[row].id).text(data[row].name));
                            }
                            $('#id_seat').trigger("change");
                        }
                    });
                });

                $('#id_seat').on('change', function() {
                    if($('#option_id_seat').val() == "modify"){
                        $('#seat_name').val($('#id_seat option:selected').text());
                    }else{
                        $('#seat_name').val("");
                    }
                    $.ajax({
                        url: '/voting/api/booths/',
                        dataType: 'json',
                        type: 'GET',
                        data: {seat_id : $('#id_seat').val()},
                        success: function(data) {
                            $('#id_booth').empty();
                            for (row in data) {
                                $('#id_booth').append($('<option></option>').attr('value', data[row].id).text(data[row].name));
                            }
                            $('#id_booth').trigger("change");
                        }
                    });
                });
                $('#id_booth').on('change', function() {
                   if($('#option_id_booth').val() == "modify"){
                        $('#booth_name').val($('#id_booth option:selected').text());
                    }
                });
               flag = false;
               $('#election_done').click(function() {
                    if(flag == false){
                        flag = true;
                    }else{
                        flag = false;
                    }
                    if(flag == true) {
                        $.ajax({
                           url: '/voting/update_election_status/',
                           type: 'POST',
                            beforeSend: function(xhr) {
                              xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                            },
                           success: function(data) {
                                $('#count_vote').html(data);
                           }
                        });
                    }else{
                        $('#count_vote').empty();
                    }
               });

                $('#state').hide();
                $('#seat').hide();
                $('#state_id').hide();
                $('#seat_id').hide();
                $('#level_id').on('change', function() {
                    level= $(this).val();
                    if(level=="state"){
                        $('#seat').hide();
                        $('#seat_id').empty().append('<option selected="selected" value="">Select a district</option>')
                        $('#seat_id').hide();
                        $('#state').show();
                        $('#state_id').show();
                    }else if(level=="seat"){
                        $('#state').show();
                        $('#state_id').show();
                        $('#state_id').trigger('change');
                        $('#seat').show();
                        $('#seat_id').show();
                    }else{
                        $('#state').hide();
                        $('#seat').hide();
                        $('#state_id').hide();
                        $('#seat_id').hide();
                    }
                });
                $('#state_id').on('change', function() {
                    if($('#level_id').val()=="seat"){
                        $.ajax({
                            url: '/voting/api/seats/',
                            dataType: 'json',
                            type: 'GET',
                            data: {state_id : $('#state_id').val()},
                            success: function(data) {
                                $('#seat_id').empty();
                                for (row in data) {
                                    $('#seat_id').append($('<option></option>').attr('value', data[row].id).text(data[row].name));
                                }

                            }
                        });
                    }
                });
            });

        </script>
    </head>
    <body style="background-image: url({%load static%}{% static "vote.jpeg" %});background-repeat: no-repeat;
    background-position: center;background-size: 100%;">
        <h1>{% block head %}{% endblock %}</h1>
        {% block content %}{% endblock %}

    </body>
</html>

voting/templates/cast_vote.html
{% extends "base.html" %}
{% block title %}Voting Page{% endblock %}
{% block head %}Cast Your Vote Here{% endblock %}
{% block content %}
    <p><a href="/voting/home/">Home</a></p>
    <form method="post" action="/voting/vote/">{% csrf_token %}
        <table border="0">
            <tr><th><label for="id_party">Party Name:</label></th>
                <td>
                 <select name="party_name">
                    {% for party in parties %}
                        <option value="{{ party.id }}">{{ party.name }}</option>
                    {% endfor %}
                 </select>
                </td>
                <td><input type="hidden" name="user" value="{{ user }}"></td>
                <td>
                   <input type="submit" value="Submit">
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

voting/templates/count_votes.html
{% extends "base.html" %}
{% block title %}Vote Counting Page{% endblock %}
{% block head %}Count Votes Here{% endblock %}
{% block content %}
    <p><a href="/voting/home/">Home</a></p>
    <form method="post" action="/voting/count_vote/">{% csrf_token %}
        <table border="0">
            <tr>
                <th><label for="id_level">Level:</label></th>
                <td>
                 <select name="level" id="level_id">
                     <option value="">Select Level</option>
                     <option value="state">state</option>
                     <option value="seat">district</option>
                     <option value="country">country</option>
                 </select>
                </td>
            </tr>
            <tr>
                <th><label for="id_state" id="state">State Name:</label></th>
                <td>
                 <select name="state_id" id="state_id">
                     {% for state in states %}
                        <option value="{{ state.id }}">{{ state.name }}</option>
                    {% endfor %}
                 </select>
                </td>
            </tr>
            <tr><th><label for="id_seat" id="seat">District Name:</label></th>
                <td>
                 <select name="seat_id" id="seat_id">
                    <option></option>
                 </select>
                </td>
                <td><input type="hidden" name="user" value="{{ user }}"></td
            </tr>
            <tr>
                <td>
                   <input type="submit" value="Submit">
                </td>
            </tr>
        </table>
    </form>
{% endblock %}